// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/cerebras.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type CEREBRAS_MODELS_GROUPS = {
	"openai-completions": {
		"gemma-4-31b": object;
		"gpt-oss-120b": object;
	};
};

export const CEREBRAS_MODELS: ModelCatalog<CEREBRAS_MODELS_GROUPS, "cerebras"> =
	flattenModelCatalog("cerebras", values as CEREBRAS_MODELS_GROUPS);
