// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/deepseek.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type DEEPSEEK_MODELS_GROUPS = {
	"openai-completions": {
		"deepseek-v4-flash": object;
		"deepseek-v4-pro": object;
	};
};

export const DEEPSEEK_MODELS: ModelCatalog<DEEPSEEK_MODELS_GROUPS, "deepseek"> =
	flattenModelCatalog("deepseek", values as DEEPSEEK_MODELS_GROUPS);
