// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/fireworks.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type FIREWORKS_MODELS_GROUPS = {
	"anthropic-messages": {
		"accounts/fireworks/models/deepseek-v4-flash": object;
		"accounts/fireworks/models/deepseek-v4-flash-0731": object;
		"accounts/fireworks/models/deepseek-v4-pro": object;
		"accounts/fireworks/models/deepseek-v4-pro-0813": object;
		"accounts/fireworks/models/gpt-oss-120b": object;
		"accounts/fireworks/models/gpt-oss-20b": object;
		"accounts/fireworks/models/inkling": object;
		"accounts/fireworks/models/kimi-k2p6": object;
		"accounts/fireworks/models/kimi-k2p7-code": object;
		"accounts/fireworks/models/minimax-m2p7": object;
		"accounts/fireworks/models/minimax-m3": object;
		"accounts/fireworks/models/muse-glimmer-30b": object;
		"accounts/fireworks/models/nemotron-3-ultra-nvfp4": object;
		"accounts/fireworks/models/nemotron-lightning-3p5-30b-a3b": object;
		"accounts/fireworks/models/qwen3p7-plus": object;
		"accounts/fireworks/models/qwen3p8-max": object;
		"accounts/fireworks/routers/kimi-k2p6-fast": object;
		"accounts/fireworks/routers/kimi-k2p6-turbo": object;
		"accounts/fireworks/routers/kimi-k2p7-code-fast": object;
	};
	"openai-completions": {
		"accounts/fireworks/models/glm-5p2": object;
		"accounts/fireworks/models/kimi-k3": object;
		"accounts/fireworks/routers/glm-5p2-fast": object;
		"accounts/fireworks/routers/kimi-k3-fast": object;
	};
};

export const FIREWORKS_MODELS: ModelCatalog<FIREWORKS_MODELS_GROUPS, "fireworks"> =
	flattenModelCatalog("fireworks", values as FIREWORKS_MODELS_GROUPS);
