// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/kimi-coding.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type KIMI_CODING_MODELS_GROUPS = {
	"anthropic-messages": {
		"k3": object;
		"k3-256k": object;
		"kimi-for-coding": object;
		"kimi-for-coding-highspeed": object;
	};
};

export const KIMI_CODING_MODELS: ModelCatalog<KIMI_CODING_MODELS_GROUPS, "kimi-coding"> =
	flattenModelCatalog("kimi-coding", values as KIMI_CODING_MODELS_GROUPS);
