// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/minimax.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type MINIMAX_MODELS_GROUPS = {
	"anthropic-messages": {
		"MiniMax-M2.7": object;
		"MiniMax-M2.7-highspeed": object;
		"MiniMax-M3": object;
	};
};

export const MINIMAX_MODELS: ModelCatalog<MINIMAX_MODELS_GROUPS, "minimax"> =
	flattenModelCatalog("minimax", values as MINIMAX_MODELS_GROUPS);
