// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/xiaomi-token-plan-ams.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type XIAOMI_TOKEN_PLAN_AMS_MODELS_GROUPS = {
	"openai-completions": {
		"mimo-v2.5": object;
		"mimo-v2.5-pro": object;
	};
};

export const XIAOMI_TOKEN_PLAN_AMS_MODELS: ModelCatalog<XIAOMI_TOKEN_PLAN_AMS_MODELS_GROUPS, "xiaomi-token-plan-ams"> =
	flattenModelCatalog("xiaomi-token-plan-ams", values as XIAOMI_TOKEN_PLAN_AMS_MODELS_GROUPS);
