// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/xiaomi.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type XIAOMI_MODELS_GROUPS = {
	"openai-completions": {
		"mimo-v2.5": object;
		"mimo-v2.5-pro": object;
		"mimo-v2.5-pro-ultraspeed": object;
	};
};

export const XIAOMI_MODELS: ModelCatalog<XIAOMI_MODELS_GROUPS, "xiaomi"> =
	flattenModelCatalog("xiaomi", values as XIAOMI_MODELS_GROUPS);
